services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:3000"
    volumes: #commented out for production use
#      - .:/app # this is watching my code live and hot loading it
      - node_modules:/app/node_modules  # this is the code living on the container
volumes:
  node_modules: